name: Build & Publish

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: lavylavenderr
          password: ${{ secrets.GH_PAT }}

      - name: Set Docker Tag
        id: date
        run: |
          DATESTAMP=$(date +%s)
          echo "::set-output name=datestamp::$DATESTAMP"

      - name: Build and push Docker images
        uses: iloveitaly/github-action-nixpacks@main
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:custom-${{ steps.date.outputs.datestamp }}
            ${{ env.IMAGE_NAME }}:latest
